pipeline {
    agent any

    environment {
        PATH = "C:\\Program Files\\Docker\\Docker\\resources\\bin;${env.PATH}"

        // Define Docker Hub credentials ID
        DOCKERHUB_CREDENTIALS_ID = 'Docker_Hub'
        DOCKER_IMAGE = 'onnikiv/sonarjenkinscalculator'
        DOCKER_TAG = 'latest'
        SONAR_HOST_URL = 'http://localhost:9000'
        SONAR_AUTH_TOKEN = credentials('SonarQubeServer')
        SONARQUBE_SCANNER = 'SonarScanner'
    }

    tools {
        maven 'Maven 3.9.9'
    }

    stages {
        stage('Setup Maven') {
            steps {
                script {
                    def mvnHome = tool name: 'Maven 3.9.9', type: 'maven'
                    env.PATH = "${mvnHome}/bin:${env.PATH}"
                }
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/onnikiv/Ohjelmistotuotantoprojekti-2-TX00EY30-3007'
            }
        }

        stage('Build') {
            steps {
                script {
                    dir('sonarjenkinscalculator') {
                        if (isUnix()) {
                            sh 'mvn clean package -DskipTests'
                        } else {
                            bat 'mvn clean package -DskipTests'
                        }
                    }
                }
            }
        }

        stage('Test & Coverage') {
            steps {
                script {
                    dir('sonarjenkinscalculator') {
                        if (isUnix()) {
                            sh 'mvn test jacoco:report'
                        } else {
                            bat 'mvn test jacoco:report'
                        }
                    }
                }
            }
        }
        stage('Publish Test Results') {
            steps {
                junit '**/target/surefire-reports/*.xml'
            }
        }

        stage('Publish Coverage Report') {
            steps {
                jacoco execPattern: '**/target/jacoco.exec'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    dir('sonarjenkinscalculator') {
                        withCredentials([string(credentialsId: 'SonarQubeServer', variable: 'SONAR_TOKEN')]) {
                            bat """
                                ${tool 'SonarScanner'}\\bin\\sonar-scanner ^
                                -Dsonar.projectKey=otp2-inclass-assignment-5 ^
                                -Dsonar.sources=src/main/java ^
                                -Dsonar.projectName=otp2-inclass-assignment-5 ^
                                -Dsonar.host.url=${SONAR_HOST_URL} ^
                                -Dsonar.token=%SONAR_TOKEN% ^
                                -Dsonar.java.binaries=target/classes
                            """
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
    }
}