CREATE DATABASE shopping_cart_db;

USE shopping_cart_db;

CREATE TABLE items (
 id INT AUTO_INCREMENT PRIMARY KEY,
 price DOUBLE NOT NULL,
 quantity INT NOT NULL
);
CREATE TABLE item_translations (
 id INT AUTO_INCREMENT PRIMARY KEY,
 item_id INT NOT NULL,
 lang VARCHAR(5) NOT NULL,
 name VARCHAR(255) NOT NULL,
 FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);